### ISSUE TITLE
Unable to run with default docker-compose config

### ISSUE THREAD

**Issue by muthu3107** [SaiAkhil066/DeepSeek-RAG-Chatbot#21]
![Image](https://github.com/user-attachments/assets/cb5602ed-ec69-4914-bddf-db9720f4c75b)

**Comment by SaiAkhil066** [comment]
Hey,

Let's resolve these Docker-related issues step by step:

**1. Version Warning Fix:**
```diff
# In docker-compose.yml
- version: '3.8'  # Remove this line
services:
  ollama:
```
Modern Docker Compose automatically handles versioning - just remove the version declaration.

**2. Ollama Image Pull Error Fix:**
The error occurs because the compose file is trying to pull from GitHub Container Registry (ghcr.io) without proper authentication. Let's modify the compose file to use the official Ollama image:

```yaml
services:
  ollama:
    image: ollama/ollama:0.1.25  # Official Docker Hub image
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

volumes:
  ollama:
```

**To fix this:**
1. Update your `docker-compose.yml` with the above configuration
2. Run these commands:
```bash
# Stop and remove existing containers
docker compose down

# Pull the new image
docker pull ollama/ollama:0.1.25

# Start fresh
docker compose up -d
```

**If you still encounter authentication issues:**
1. Verify your Docker login status:
```bash
docker logout ghcr.io  # Remove GitHub registry credentials if not needed
docker login  # Ensure you're logged into Docker Hub
```

2. Check network connectivity:
```bash
curl -v https://registry-1.docker.io/v2/  # Test Docker Hub connectivity
```

**Additional Notes:**
- The official Ollama image requires ARM64 architecture support. If you're on a different architecture, you may need to build from source.
- Consider using a specific version tag instead of `latest` to avoid breaking changes
- Ensure you have at least 2GB RAM allocated to Docker
